// Skills
export const ADD_NEW_SKILL_SUCCESS = 'ADD_NEW_SKILL_SUCCESS';
export const REMOVE_SKILL_SUCCESS = 'REMOVE_SKILL_SUCCESS';

// Main information
export const CHANGE_MAIN_INFORMATION = 'CHANGE_MAIN_INFORMATION';

// Portfolio
export const ADD_NEW_PORTFOLIO_SUCCESS = 'ADD_NEW_PORTFOLIO_SUCCESS';
export const REMOVE_PORTFOLIO_SUCCESS = 'REMOVE_PORTFOLIO_SUCCESS';

// Experience
export const ADD_NEW_EXPERIENCE_SUCCESS = 'ADD_NEW_EXPERIENCE_SUCCESS';
export const REMOVE_EXPERIENCE_SUCCESS = 'REMOVE_EXPERIENCE_SUCCESS';